# Generated by Django 4.0.5 on 2022-06-14 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Products_prices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='supermarket_branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='Products_prices.supermarketbranch'),
        ),
    ]
