# Generated by Django 4.0.5 on 2022-06-15 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products_prices', '0002_item_supermarket_branch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='name',
        ),
    ]
