# Generated by Django 4.0.5 on 2022-06-25 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products_prices', '0004_product_branch_alter_item_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='branch',
        ),
    ]
