# Generated by Django 4.0.5 on 2022-06-26 12:19

from django.db import migrations, models
import uuid

class Migration(migrations.Migration):

    dependencies = [
        ('Products_prices', '0006_item_slug_product_slug_supermarketbranch_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='slug',
            field=models.SlugField(default=uuid.uuid1, null=True, blank=True),
        ),
        migrations.AddField(
            model_name='catagory',
            name='slug',
            field=models.SlugField(default=uuid.uuid1, null=True, blank=True),
        ),
        migrations.AddField(
            model_name='supermarket',
            name='slug',
            field=models.SlugField(default=uuid.uuid1, null=True, blank=True),
        ),
    ]
