# Generated by Django 4.0.5 on 2022-06-26 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products_prices', '0009_alter_brand_slug_alter_catagory_slug_alter_item_slug_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='catagory',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='item',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='supermarket',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='supermarketbranch',
            name='slug',
        ),
    ]
