# Generated by Django 4.0.5 on 2022-06-26 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products_prices', '0010_remove_brand_slug_remove_catagory_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='slug',
            field=models.SlugField(blank=True, null=True,),
        ),
        migrations.AddField(
            model_name='catagory',
            name='slug',
            field=models.SlugField(blank=True, null=True,),
        ),
        migrations.AddField(
            model_name='item',
            name='slug',
            field=models.SlugField(blank=True, null=True,),
        ),
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, null=True,),
        ),
        migrations.AddField(
            model_name='supermarket',
            name='slug',
            field=models.SlugField(blank=True, null=True,),
        ),
        migrations.AddField(
            model_name='supermarketbranch',
            name='slug',
            field=models.SlugField(blank=True, null=True,),
        ),
    ]
