# Generated by Django 4.0.5 on 2022-06-26 19:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Products_prices', '0014_brand_slug_catagory_slug_item_slug_product_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catagory',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.uuid1, null=True),
        ),
    ]
