# Generated by Django 4.0.5 on 2022-06-28 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products_prices', '0016_remove_brand_slug_remove_catagory_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='supermarketbranch',
            name='city',
            field=models.CharField(blank=True, help_text='set the City name', max_length=50, null=True),
        ),
    ]
