# Generated by Django 4.0.5 on 2022-07-08 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products_prices', '0017_item_slug_alter_supermarketbranch_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Product Price'),
        ),
    ]
