# Generated by Django 4.0.5 on 2022-07-08 19:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Products_prices', '0018_alter_item_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cunsomer',
            fields=[
                ('first_name', models.CharField(max_length=50, verbose_name='First name')),
                ('middel_name', models.CharField(max_length=50, verbose_name='Middel name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last name')),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False, unique=True, verbose_name='User Email')),
                ('phone_no', models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='Phone Number')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
