# Generated by Django 4.0.5 on 2022-07-08 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products_prices', '0019_cunsomer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cunsomer',
        ),
    ]
