# Generated by Django 4.0.5 on 2022-07-15 19:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Products_prices', '0023_consumer_alter_item_creator_delete_cunsomer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumer',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
