# Generated by Django 4.0.5 on 2022-07-17 02:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Products_prices', '0024_alter_consumer_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='creator',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='Products_prices.consumer'),
        ),
    ]
