# Generated by Django 4.0.5 on 2022-08-21 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products_prices', '0026_alter_item_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumer',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='First name'),
        ),
        migrations.AlterField(
            model_name='consumer',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Last name'),
        ),
        migrations.AlterField(
            model_name='consumer',
            name='phone_no',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True, verbose_name='Phone Number'),
        ),
    ]
